# Generated by Django 4.2.7 on 2025-06-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1500, null=True, unique=True),
        ),
    ]
